graph TD

    ROLES ||--o{ USERS : "assigns"
    USERS ||--o{ LOGIN_ATTEMPTS : "makes"
    USERS ||--o{ RENTAL_CONTRACTS : "processes"
    USERS ||--o{ RENTAL_CONTRACTS : "rents"
    EQUIPMENT ||--o{ RENTAL_CONTRACTS : "rented in"
    RENTAL_CONTRACTS ||--o{ RETURNS : "has"
    RENTAL_CONTRACTS ||--o{ PENALTIES : "has"

    ROLES {
        int id PK
        string name
    }

    USERS {
        int id PK
        string login UK
        string password_hash
        string password_salt
        int role_id FK
        timestamp created_at
    }

    LOGIN_ATTEMPTS {
        int id PK
        int user_id FK
        boolean is_success
        string message
        timestamp created_at
    }

    EQUIPMENT {
        int id PK
        string name
        string category
        string status
        decimal price_per_day
        string serial_number UK
        text description
        int quantity
        timestamp created_at
    }

    RENTAL_CONTRACTS {
        int id PK
        int customer_id FK
        int processed_by_user_id FK
        string contract_number UK
        date rental_start_date
        date rental_end_date
        decimal total_cost
        string status
        timestamp created_at
    }

    RETURNS {
        int id PK
        int contract_id FK
        date actual_return_date
        date expected_return_date
        int days_over_due
        text notes
        timestamp created_at
    }

    PENALTIES {
        int id PK
        int rental_contract_id FK
        string penalty_type
        decimal amount
        date issued_date
        string status
        text description
        timestamp created_at
    }
